# How to run:

version: '2'
services:
  revivarqdb:
    container_name: revivarqdb
    image: 'mongo'
    volumes:
      - /vol/ages-revivarq/MongoDB:/data/db
    ports:
      - '4502:27017'
    networks:
      - revivarq-network

  revivarqapi:
    container_name: revivarqapi
    build:
      context: .
      dockerfile: Dockerfile_api
    image: revivarq-api:latest
    depends_on:
      - "revivarqdb"
    expose:
      - "4000"
    ports:
      - "4501:4000"
    environment:
      - NODE_ENV=production
    command: ["./wait-for-it.sh", "-t", "0", "revivarqdb:27017", "--", "npm","start", ]
    networks:
      - revivarq-network

networks:
  revivarq-network:
